<?php
/**
 * Asset dependencies for AI Content Optimizer
 *
 * This file is auto-generated by the build process.
 * For development, you can use this as a template.
 */

return array(
	'dependencies' => array(
		'wp-plugins',
		'wp-element',
		'wp-components',
		'wp-editor',
		'wp-data',
		'wp-i18n',
	),
	'version'      => '1.0.0',
);
